<?php

function iworks_kpir_options() {
	$iworks_kpir_options = array();
	/**
	 * main settings
	 */
	$iworks_kpir_options['index'] = array(
		'version'    => '0.0',
		'page_title' => __( 'Configuration', 'kpir' ),
		'menu'       => 'submenu',
		'parent'     => add_query_arg(
			array(
				'post_type' => 'iworks_kpir_invoice',
			),
			'edit.php'
		),
		'options'    => array(
			array(
				'name'              => 'nip',
				'type'              => 'text',
				'class'             => 'regular-text',
				'th'                => __( 'NIP', 'kpir' ),
				'sanitize_callback' => 'esc_html',
			),
			array(
				'name'              => 'name',
				'type'              => 'text',
				'class'             => 'regular-text',
				'th'                => __( 'Full Name', 'kpir' ),
				'sanitize_callback' => 'esc_html',
			),
			array(
				'name'              => 'email',
				'type'              => 'email',
				'class'             => 'regular-text',
				'th'                => __( 'E-Mail', 'kpir' ),
				'sanitize_callback' => 'esc_html',
			),
			array(
				'name'              => 'department_of_revenue',
				'type'              => 'select2',
				'class'             => 'regular-text',
				'th'                => __( 'Department of Revenue', 'kpir' ),
				'sanitize_callback' => 'esc_html',
				'options'           => iworks_kpir_get_deprtments_ofrevenue(),
			),
			array(
				'name'              => 'phone',
				'type'              => 'text',
				'class'             => 'regular-text',
				'th'                => __( 'Phone', 'kpir' ),
				'sanitize_callback' => 'esc_html',
			),
		),
		//      'metaboxes' => array(),
		'pages'      => array(
			'report_monthly'  => array(
				'page_title'         => __( 'Monthly Report', 'kpir' ),
				'menu_title'         => __( 'Monthly', 'kpir' ),
				'menu'               => 'submenu',
				'parent'             => add_query_arg(
					array(
						'post_type' => 'iworks_kpir_invoice',
					),
					'edit.php'
				),
				'show_page_callback' => 'iworks_kpir_report_monthly',
			),
			'jpk_vat_3'       => array(
				'page_title'         => __( 'JPK VAT(3)', 'kpir' ),
				'menu'               => 'submenu',
				'parent'             => add_query_arg(
					array(
						'post_type' => 'iworks_kpir_invoice',
					),
					'edit.php'
				),
				'show_page_callback' => 'iworks_kpir_jpk_vat_3',
			),
			'jpk_v7m'         => array(
				'page_title'         => __( 'JPK V7M', 'kpir' ),
				'menu'               => 'submenu',
				'parent'             => add_query_arg(
					array(
						'post_type' => 'iworks_kpir_invoice',
					),
					'edit.php'
				),
				'show_page_callback' => 'iworks_kpir_jpk_v7m',
			),
			'report_annually' => array(
				'page_title'         => __( 'Annually Report', 'kpir' ),
				'menu_title'         => __( 'Annually', 'kpir' ),
				'menu'               => 'submenu',
				'parent'             => add_query_arg(
					array(
						'post_type' => 'iworks_kpir_invoice',
					),
					'edit.php'
				),
				'show_page_callback' => 'iworks_kpir_report_annually',
			),
		),
	);
	return $iworks_kpir_options;
}

function iworks_kpir_report_monthly() {
	 global $iworks_kpir;
	$iworks_kpir->show_page_reports( 'monthly' );
}

function iworks_kpir_report_annually() {
	global $iworks_kpir;
	$iworks_kpir->show_page_reports( 'annually' );
}

function iworks_kpir_jpk_vat_3() {
	global $iworks_kpir;
	$iworks_kpir->show_page_jpk_vat_3();
}

function iworks_kpir_jpk_v7m() {
	global $iworks_kpir;
	$iworks_kpir->show_page_jpk_v7m();
}

function iworks_kpir_get_deprtments_ofrevenue() {
	$data = array(
		'0271' => 'Dolnośląski Urząd Skarbowy We Wrocławiu',
		'1472' => 'Drugi Mazowiecki Urząd Skarbowy w Warszawie',
		'2472' => 'Drugi Śląski Urząd Skarbowy w Bielsku-Białej',
		'1228' => 'Drugi Urząd Skarbowy Kraków',
		'1009' => 'Drugi Urząd Skarbowy Łódź-Bałuty',
		'1011' => 'Drugi Urząd Skarbowy Łódź-Górna',
		'2004' => 'Drugi Urząd Skarbowy w Białymstoku',
		'2404' => 'Drugi Urząd Skarbowy w Bielsku-Białej',
		'0405' => 'Drugi Urząd Skarbowy w Bydgoszczy',
		'2410' => 'Drugi Urząd Skarbowy w Częstochowie',
		'2206' => 'Drugi Urząd Skarbowy w Gdańsku',
		'2209' => 'Drugi Urząd Skarbowy w Gdyni',
		'2413' => 'Drugi Urząd Skarbowy w Gliwicach',
		'3008' => 'Drugi Urząd Skarbowy w Kaliszu',
		'2417' => 'Drugi Urząd Skarbowy w Katowicach',
		'2605' => 'Drugi Urząd Skarbowy w Kielcach',
		'3211' => 'Drugi Urząd Skarbowy w Koszalinie',
		'0611' => 'Drugi Urząd Skarbowy w Lublinie',
		'1610' => 'Drugi Urząd Skarbowy w Opolu',
		'1425' => 'Drugi Urząd Skarbowy w Radomiu',
		'1822' => 'Drugi Urząd Skarbowy w Rzeszowie',
		'3216' => 'Drugi Urząd Skarbowy w Szczecinie',
		'1224' => 'Drugi Urząd Skarbowy w Tarnowie',
		'0417' => 'Drugi Urząd Skarbowy w Toruniu',
		'0809' => 'Drugi Urząd Skarbowy w Zielonej Górze',
		'1436' => 'Drugi Urząd Skarbowy Warszawa-Śródmieście',
		'3072' => 'Drugi Wielkopolski Urząd Skarbowy w Kaliszu',
		'0471' => 'Kujawsko-Pomorski Urząd Skarbowy w Bydgoszczy',
		'0671' => 'Lubelski Urząd Skarbowy w Lublinie',
		'0871' => 'Lubuski Urząd Skarbowy w Zielonej Górze',
		'1071' => 'Łódzki Urząd Skarbowy w Łodzi',
		'1271' => 'Małopolski Urząd Skarbowy w Krakowie',
		'1671' => 'Opolski Urząd Skarbowy w Opolu',
		'1471' => 'Pierwszy Mazowiecki Urząd Skarbowy w Warszawie',
		'2471' => 'Pierwszy Śląski Urząd Skarbowy w Sosnowcu',
		'1207' => 'Pierwszy Urząd Skarbowy Kraków',
		'1008' => 'Pierwszy Urząd Skarbowy Łódź-Bałuty',
		'1010' => 'Pierwszy Urząd Skarbowy Łódź-Górna',
		'2003' => 'Pierwszy Urząd Skarbowy w Białymstoku',
		'2403' => 'Pierwszy Urząd Skarbowy w Bielsku-Białej',
		'0404' => 'Pierwszy Urząd Skarbowy w Bydgoszczy',
		'2409' => 'Pierwszy Urząd Skarbowy w Częstochowie',
		'2205' => 'Pierwszy Urząd Skarbowy w Gdańsku',
		'2208' => 'Pierwszy Urząd Skarbowy w Gdyni',
		'2412' => 'Pierwszy Urząd Skarbowy w Gliwicach',
		'3007' => 'Pierwszy Urząd Skarbowy w Kaliszu',
		'2416' => 'Pierwszy Urząd Skarbowy w Katowicach',
		'2604' => 'Pierwszy Urząd Skarbowy w Kielcach',
		'3210' => 'Pierwszy Urząd Skarbowy w Koszalinie',
		'0610' => 'Pierwszy Urząd Skarbowy w Lublinie',
		'1609' => 'Pierwszy Urząd Skarbowy w Opolu',
		'3023' => 'Pierwszy Urząd Skarbowy w Poznaniu',
		'1424' => 'Pierwszy Urząd Skarbowy w Radomiu',
		'1816' => 'Pierwszy Urząd Skarbowy w Rzeszowie',
		'3215' => 'Pierwszy Urząd Skarbowy w Szczecinie',
		'1223' => 'Pierwszy Urząd Skarbowy w Tarnowie',
		'0416' => 'Pierwszy Urząd Skarbowy w Toruniu',
		'0808' => 'Pierwszy Urząd Skarbowy w Zielonej Górze',
		'1435' => 'Pierwszy Urząd Skarbowy Warszawa-Śródmieście',
		'0229' => 'Pierwszy Urząd Skarbowy We Wrocławiu',
		'3071' => 'Pierwszy Wielkopolski Urząd Skarbowy w Poznaniu',
		'1871' => 'Podkarpacki Urząd Skarbowy w Rzeszowie',
		'2071' => 'Podlaski Urząd Skarbowy w Białymstoku',
		'2271' => 'Pomorski Urząd Skarbowy w Gdańsku',
		'2671' => 'Świętokrzyski Urząd Skarbowy w Kielcach',
		'1473' => 'Trzeci Mazowiecki Urząd Skarbowy w Radomiu',
		'0406' => 'Trzeci Urząd Skarbowy w Bydgoszczy',
		'2207' => 'Trzeci Urząd Skarbowy w Gdańsku',
		'0612' => 'Trzeci Urząd Skarbowy w Lublinie',
		'3217' => 'Trzeci Urząd Skarbowy w Szczecinie',
		'1449' => 'Trzeci Urząd Skarbowy Warszawa-Śródmieście',
		'1208' => 'Urząd Skarbowy Kraków-Krowodrza',
		'1209' => 'Urząd Skarbowy Kraków-Nowa Huta',
		'1210' => 'Urząd Skarbowy Kraków-Podgórze',
		'1211' => 'Urząd Skarbowy Kraków-Prądnik',
		'1212' => 'Urząd Skarbowy Kraków-Stare Miasto',
		'1213' => 'Urząd Skarbowy Kraków-Śródmieście',
		'1012' => 'Urząd Skarbowy Łódź-Polesie',
		'1013' => 'Urząd Skarbowy Łódź-Śródmieście',
		'1014' => 'Urząd Skarbowy Łódź-Widzew',
		'3020' => 'Urząd Skarbowy Poznań-Grunwald',
		'3021' => 'Urząd Skarbowy Poznań-Jeżyce',
		'3022' => 'Urząd Skarbowy Poznań-Nowe Miasto',
		'3026' => 'Urząd Skarbowy Poznań-Wilda',
		'3025' => 'Urząd Skarbowy Poznań-Winogrady',
		'0402' => 'Urząd Skarbowy w Aleksandrowie Kujawskim',
		'2002' => 'Urząd Skarbowy w Augustowie',
		'2802' => 'Urząd Skarbowy w Bartoszycach',
		'1002' => 'Urząd Skarbowy w Bełchatowie',
		'2402' => 'Urząd Skarbowy w Będzinie',
		'0602' => 'Urząd Skarbowy w Białej Podlaskiej',
		'1402' => 'Urząd Skarbowy w Białobrzegach',
		'3202' => 'Urząd Skarbowy w Białogardzie',
		'2005' => 'Urząd Skarbowy w Bielsku Podlaskim',
		'0603' => 'Urząd Skarbowy w Biłgoraju',
		'1202' => 'Urząd Skarbowy w Bochni',
		'0202' => 'Urząd Skarbowy w Bolesławcu',
		'2803' => 'Urząd Skarbowy w Braniewie',
		'0403' => 'Urząd Skarbowy w Brodnicy',
		'1602' => 'Urząd Skarbowy w Brzegu',
		'1203' => 'Urząd Skarbowy w Brzesku',
		'1003' => 'Urząd Skarbowy w Brzezinach',
		'1802' => 'Urząd Skarbowy w Brzozowie',
		'2602' => 'Urząd Skarbowy w Busku-Zdroju',
		'0203' => 'Urząd Skarbowy w Bystrzycy Kłodzkiej',
		'2405' => 'Urząd Skarbowy w Bytomiu',
		'2202' => 'Urząd Skarbowy w Bytowie',
		'0604' => 'Urząd Skarbowy w Chełmie',
		'0407' => 'Urząd Skarbowy w Chełmnie',
		'3037' => 'Urząd Skarbowy w Chodzieży',
		'2203' => 'Urząd Skarbowy w Chojnicach',
		'2406' => 'Urząd Skarbowy w Chorzowie',
		'3203' => 'Urząd Skarbowy w Choszcznie',
		'1204' => 'Urząd Skarbowy w Chrzanowie',
		'1403' => 'Urząd Skarbowy w Ciechanowie',
		'2407' => 'Urząd Skarbowy w Cieszynie',
		'3002' => 'Urząd Skarbowy w Czarnkowie',
		'2408' => 'Urząd Skarbowy w Czechowicach-Dziedzicach',
		'2204' => 'Urząd Skarbowy w Człuchowie',
		'2411' => 'Urząd Skarbowy w Dąbrowie Górniczej',
		'1205' => 'Urząd Skarbowy w Dąbrowie Tarnowskiej',
		'1803' => 'Urząd Skarbowy w Dębicy',
		'3204' => 'Urząd Skarbowy w Drawsku Pomorskim',
		'0812' => 'Urząd Skarbowy w Drezdenku',
		'2804' => 'Urząd Skarbowy w Działdowie',
		'0204' => 'Urząd Skarbowy w Dzierżoniowie',
		'2805' => 'Urząd Skarbowy w Elblągu',
		'2806' => 'Urząd Skarbowy w Ełku',
		'1404' => 'Urząd Skarbowy w Garwolinie',
		'2807' => 'Urząd Skarbowy w Giżycku',
		'0205' => 'Urząd Skarbowy w Głogowie',
		'1004' => 'Urząd Skarbowy w Głownie',
		'1603' => 'Urząd Skarbowy w Głubczycach',
		'3003' => 'Urząd Skarbowy w Gnieźnie',
		'3205' => 'Urząd Skarbowy w Goleniowie',
		'0422' => 'Urząd Skarbowy w Golubiu-Dobrzyniu',
		'1206' => 'Urząd Skarbowy w Gorlicach',
		'0802' => 'Urząd Skarbowy w Gorzowie Wielkopolskim',
		'1405' => 'Urząd Skarbowy w Gostyninie',
		'3004' => 'Urząd Skarbowy w Gostyniu',
		'0233' => 'Urząd Skarbowy w Górze',
		'2006' => 'Urząd Skarbowy w Grajewie',
		'1406' => 'Urząd Skarbowy w Grodzisku Mazowieckim',
		'3005' => 'Urząd Skarbowy w Grodzisku Wielkopolskim',
		'1407' => 'Urząd Skarbowy w Grójcu',
		'0408' => 'Urząd Skarbowy w Grudziądzu',
		'3206' => 'Urząd Skarbowy w Gryficach',
		'3207' => 'Urząd Skarbowy w Gryfinie',
		'2015' => 'Urząd Skarbowy w Hajnówce',
		'0605' => 'Urząd Skarbowy w Hrubieszowie',
		'2808' => 'Urząd Skarbowy w Iławie',
		'0409' => 'Urząd Skarbowy w Inowrocławiu',
		'0606' => 'Urząd Skarbowy w Janowie Lubelskim',
		'3006' => 'Urząd Skarbowy w Jarocinie',
		'1804' => 'Urząd Skarbowy w Jarosławiu',
		'2414' => 'Urząd Skarbowy w Jastrzębiu-Zdroju',
		'1805' => 'Urząd Skarbowy w Jaśle',
		'0206' => 'Urząd Skarbowy w Jaworze',
		'2415' => 'Urząd Skarbowy w Jaworznie',
		'0207' => 'Urząd Skarbowy w Jeleniej Górze',
		'2603' => 'Urząd Skarbowy w Jędrzejowie',
		'3208' => 'Urząd Skarbowy w Kamieniu Pomorskim',
		'0208' => 'Urząd Skarbowy w Kamiennej Górze',
		'2210' => 'Urząd Skarbowy w Kartuzach',
		'2614' => 'Urząd Skarbowy w Kazimierzy Wielkiej',
		'1604' => 'Urząd Skarbowy w Kędzierzynie-Koźlu',
		'3009' => 'Urząd Skarbowy w Kępnie',
		'2809' => 'Urząd Skarbowy w Kętrzynie',
		'1605' => 'Urząd Skarbowy w Kluczborku',
		'2418' => 'Urząd Skarbowy w Kłobucku',
		'0209' => 'Urząd Skarbowy w Kłodzku',
		'1806' => 'Urząd Skarbowy w Kolbuszowej',
		'3010' => 'Urząd Skarbowy w Kole',
		'2007' => 'Urząd Skarbowy w Kolnie',
		'3209' => 'Urząd Skarbowy w Kołobrzegu',
		'3011' => 'Urząd Skarbowy w Koninie',
		'2606' => 'Urząd Skarbowy w Końskich',
		'3012' => 'Urząd Skarbowy w Kościanie',
		'2211' => 'Urząd Skarbowy w Kościerzynie',
		'1408' => 'Urząd Skarbowy w Kozienicach',
		'1613' => 'Urząd Skarbowy w Krapkowicach',
		'0607' => 'Urząd Skarbowy w Krasnymstawie',
		'0608' => 'Urząd Skarbowy w Kraśniku',
		'1807' => 'Urząd Skarbowy w Krośnie',
		'0803' => 'Urząd Skarbowy w Krośnie Odrzańskim',
		'3013' => 'Urząd Skarbowy w Krotoszynie',
		'1005' => 'Urząd Skarbowy w Kutnie',
		'2212' => 'Urząd Skarbowy w Kwidzynie',
		'1409' => 'Urząd Skarbowy w Legionowie',
		'0210' => 'Urząd Skarbowy w Legnicy',
		'1808' => 'Urząd Skarbowy w Lesku',
		'3014' => 'Urząd Skarbowy w Lesznie',
		'1809' => 'Urząd Skarbowy w Leżajsku',
		'2213' => 'Urząd Skarbowy w Lęborku',
		'1214' => 'Urząd Skarbowy w Limanowej',
		'0410' => 'Urząd Skarbowy w Lipnie',
		'1447' => 'Urząd Skarbowy w Lipsku',
		'1810' => 'Urząd Skarbowy w Lubaczowie',
		'0211' => 'Urząd Skarbowy w Lubaniu',
		'0609' => 'Urząd Skarbowy w Lubartowie',
		'0212' => 'Urząd Skarbowy w Lubinie',
		'2419' => 'Urząd Skarbowy w Lublińcu',
		'0213' => 'Urząd Skarbowy w Lwówku Śląskim',
		'1811' => 'Urząd Skarbowy w Łańcucie',
		'1006' => 'Urząd Skarbowy w Łasku',
		'0621' => 'Urząd Skarbowy w Łęcznej',
		'1028' => 'Urząd Skarbowy w Łęczycy',
		'2008' => 'Urząd Skarbowy w Łomży',
		'1410' => 'Urząd Skarbowy w Łosicach',
		'1007' => 'Urząd Skarbowy w Łowiczu',
		'0613' => 'Urząd Skarbowy w Łukowie',
		'1411' => 'Urząd Skarbowy w Makowie Mazowieckim',
		'2214' => 'Urząd Skarbowy w Malborku',
		'1215' => 'Urząd Skarbowy w Miechowie',
		'1812' => 'Urząd Skarbowy w Mielcu',
		'3015' => 'Urząd Skarbowy w Międzychodzie',
		'0804' => 'Urząd Skarbowy w Międzyrzeczu',
		'2420' => 'Urząd Skarbowy w Mikołowie',
		'0214' => 'Urząd Skarbowy w Miliczu',
		'1412' => 'Urząd Skarbowy w Mińsku Mazowieckim',
		'1413' => 'Urząd Skarbowy w Mławie',
		'0411' => 'Urząd Skarbowy w Mogilnie',
		'2009' => 'Urząd Skarbowy w Mońkach',
		'2421' => 'Urząd Skarbowy w Mysłowicach',
		'2422' => 'Urząd Skarbowy w Myszkowie',
		'1216' => 'Urząd Skarbowy w Myślenicach',
		'3212' => 'Urząd Skarbowy w Myśliborzu',
		'0412' => 'Urząd Skarbowy w Nakle Nad Notecią',
		'1606' => 'Urząd Skarbowy w Namysłowie',
		'2810' => 'Urząd Skarbowy w Nidzicy',
		'1823' => 'Urząd Skarbowy w Nisku',
		'0215' => 'Urząd Skarbowy w Nowej Rudzie',
		'0805' => 'Urząd Skarbowy w Nowej Soli',
		'1414' => 'Urząd Skarbowy w Nowym Dworze Mazowieckim',
		'2811' => 'Urząd Skarbowy w Nowym Mieście Lubawskim',
		'1217' => 'Urząd Skarbowy w Nowym Sączu',
		'1218' => 'Urząd Skarbowy w Nowym Targu',
		'3016' => 'Urząd Skarbowy w Nowym Tomyślu',
		'1607' => 'Urząd Skarbowy w Nysie',
		'3038' => 'Urząd Skarbowy w Obornikach',
		'2812' => 'Urząd Skarbowy w Olecku',
		'0216' => 'Urząd Skarbowy w Oleśnicy',
		'1608' => 'Urząd Skarbowy w Oleśnie',
		'1219' => 'Urząd Skarbowy w Olkuszu',
		'2813' => 'Urząd Skarbowy w Olsztynie',
		'0217' => 'Urząd Skarbowy w Oławie',
		'2607' => 'Urząd Skarbowy w Opatowie',
		'1015' => 'Urząd Skarbowy w Opocznie',
		'0614' => 'Urząd Skarbowy w Opolu Lubelskim',
		'1415' => 'Urząd Skarbowy w Ostrołęce',
		'2608' => 'Urząd Skarbowy w Ostrowcu Świętokrzyskim',
		'1416' => 'Urząd Skarbowy w Ostrowi Mazowieckiej',
		'3017' => 'Urząd Skarbowy w Ostrowie Wielkopolskim',
		'2814' => 'Urząd Skarbowy w Ostródzie',
		'3018' => 'Urząd Skarbowy w Ostrzeszowie',
		'1220' => 'Urząd Skarbowy w Oświęcimiu',
		'1417' => 'Urząd Skarbowy w Otwocku',
		'1016' => 'Urząd Skarbowy w Pabianicach',
		'1029' => 'Urząd Skarbowy w Pajęcznie',
		'0615' => 'Urząd Skarbowy w Parczewie',
		'1418' => 'Urząd Skarbowy w Piasecznie',
		'2423' => 'Urząd Skarbowy w Piekarach Śląskich',
		'3019' => 'Urząd Skarbowy w Pile',
		'2609' => 'Urząd Skarbowy w Pińczowie',
		'1017' => 'Urząd Skarbowy w Piotrkowie Trybunalskim',
		'2815' => 'Urząd Skarbowy w Piszu',
		'3039' => 'Urząd Skarbowy w Pleszewie',
		'1419' => 'Urząd Skarbowy w Płocku',
		'1420' => 'Urząd Skarbowy w Płońsku',
		'1018' => 'Urząd Skarbowy w Poddębicach',
		'0234' => 'Urząd Skarbowy w Polkowicach',
		'1221' => 'Urząd Skarbowy w Proszowicach',
		'1611' => 'Urząd Skarbowy w Prudniku',
		'2221' => 'Urząd Skarbowy w Pruszczu Gdańskim',
		'1421' => 'Urząd Skarbowy w Pruszkowie',
		'1422' => 'Urząd Skarbowy w Przasnyszu',
		'1813' => 'Urząd Skarbowy w Przemyślu',
		'1814' => 'Urząd Skarbowy w Przeworsku',
		'1448' => 'Urząd Skarbowy w Przysusze',
		'2424' => 'Urząd Skarbowy w Pszczynie',
		'2215' => 'Urząd Skarbowy w Pucku',
		'0616' => 'Urząd Skarbowy w Puławach',
		'1423' => 'Urząd Skarbowy w Pułtusku',
		'3213' => 'Urząd Skarbowy w Pyrzycach',
		'2425' => 'Urząd Skarbowy w Raciborzu',
		'1019' => 'Urząd Skarbowy w Radomsku',
		'0413' => 'Urząd Skarbowy w Radziejowie',
		'0617' => 'Urząd Skarbowy w Radzyniu Podlaskim',
		'3027' => 'Urząd Skarbowy w Rawiczu',
		'1020' => 'Urząd Skarbowy w Rawie Mazowieckiej',
		'1815' => 'Urząd Skarbowy w Ropczycach',
		'2426' => 'Urząd Skarbowy w Rudzie Śląskiej',
		'2427' => 'Urząd Skarbowy w Rybniku',
		'0622' => 'Urząd Skarbowy w Rykach',
		'0414' => 'Urząd Skarbowy w Rypinie',
		'2610' => 'Urząd Skarbowy w Sandomierzu',
		'1817' => 'Urząd Skarbowy w Sanoku',
		'0423' => 'Urząd Skarbowy w Sępólnie Krajeńskim',
		'1426' => 'Urząd Skarbowy w Siedlcach',
		'2428' => 'Urząd Skarbowy w Siemianowicach Śląskich',
		'2010' => 'Urząd Skarbowy w Siemiatyczach',
		'1021' => 'Urząd Skarbowy w Sieradzu',
		'1427' => 'Urząd Skarbowy w Sierpcu',
		'2611' => 'Urząd Skarbowy w Skarżysku-Kamiennej',
		'1022' => 'Urząd Skarbowy w Skierniewicach',
		'0806' => 'Urząd Skarbowy w Słubicach',
		'3028' => 'Urząd Skarbowy w Słupcy',
		'2216' => 'Urząd Skarbowy w Słupsku',
		'1428' => 'Urząd Skarbowy w Sochaczewie',
		'1429' => 'Urząd Skarbowy w Sokołowie Podlaskim',
		'2011' => 'Urząd Skarbowy w Sokółce',
		'2217' => 'Urząd Skarbowy w Sopocie',
		'2429' => 'Urząd Skarbowy w Sosnowcu',
		'1818' => 'Urząd Skarbowy w Stalowej Woli',
		'2612' => 'Urząd Skarbowy w Starachowicach',
		'3214' => 'Urząd Skarbowy w Stargardzie',
		'2218' => 'Urząd Skarbowy w Starogardzie Gdańskim',
		'2613' => 'Urząd Skarbowy w Staszowie',
		'1612' => 'Urząd Skarbowy w Strzelcach Opolskich',
		'0218' => 'Urząd Skarbowy w Strzelinie',
		'1819' => 'Urząd Skarbowy w Strzyżowie',
		'1222' => 'Urząd Skarbowy w Suchej Beskidzkiej',
		'0813' => 'Urząd Skarbowy w Sulęcinie',
		'2012' => 'Urząd Skarbowy w Suwałkach',
		'3029' => 'Urząd Skarbowy w Szamotułach',
		'3218' => 'Urząd Skarbowy w Szczecinku',
		'2816' => 'Urząd Skarbowy w Szczytnie',
		'1430' => 'Urząd Skarbowy w Szydłowcu',
		'3030' => 'Urząd Skarbowy w Śremie',
		'0219' => 'Urząd Skarbowy w Środzie Śląskiej',
		'3031' => 'Urząd Skarbowy w Środzie Wielkopolskiej',
		'0220' => 'Urząd Skarbowy w Świdnicy',
		'0807' => 'Urząd Skarbowy w Świebodzinie',
		'0415' => 'Urząd Skarbowy w Świeciu',
		'3219' => 'Urząd Skarbowy w Świnoujściu',
		'1820' => 'Urząd Skarbowy w Tarnobrzegu',
		'2430' => 'Urząd Skarbowy w Tarnowskich Górach',
		'2219' => 'Urząd Skarbowy w Tczewie',
		'0618' => 'Urząd Skarbowy w Tomaszowie Lubelskim',
		'1023' => 'Urząd Skarbowy w Tomaszowie Mazowieckim',
		'0221' => 'Urząd Skarbowy w Trzebnicy',
		'0418' => 'Urząd Skarbowy w Tucholi',
		'3032' => 'Urząd Skarbowy w Turku',
		'2431' => 'Urząd Skarbowy w Tychach',
		'1821' => 'Urząd Skarbowy w Ustrzykach Dolnych',
		'1225' => 'Urząd Skarbowy w Wadowicach',
		'0222' => 'Urząd Skarbowy w Wałbrzychu',
		'3220' => 'Urząd Skarbowy w Wałczu',
		'0419' => 'Urząd Skarbowy w Wąbrzeźnie',
		'3033' => 'Urząd Skarbowy w Wągrowcu',
		'2220' => 'Urząd Skarbowy w Wejherowie',
		'1441' => 'Urząd Skarbowy w Węgrowie',
		'1226' => 'Urząd Skarbowy w Wieliczce',
		'1024' => 'Urząd Skarbowy w Wieluniu',
		'1027' => 'Urząd Skarbowy w Wieruszowie',
		'2432' => 'Urząd Skarbowy w Wodzisławiu Śląskim',
		'3034' => 'Urząd Skarbowy w Wolsztynie',
		'1442' => 'Urząd Skarbowy w Wołominie',
		'0223' => 'Urząd Skarbowy w Wołowie',
		'2013' => 'Urząd Skarbowy w Wysokiem Mazowieckiem',
		'1443' => 'Urząd Skarbowy w Wyszkowie',
		'2433' => 'Urząd Skarbowy w Zabrzu',
		'1227' => 'Urząd Skarbowy w Zakopanem',
		'2014' => 'Urząd Skarbowy w Zambrowie',
		'0620' => 'Urząd Skarbowy w Zamościu',
		'2434' => 'Urząd Skarbowy w Zawierciu',
		'0230' => 'Urząd Skarbowy w Ząbkowicach Śląskich',
		'1025' => 'Urząd Skarbowy w Zduńskiej Woli',
		'1026' => 'Urząd Skarbowy w Zgierzu',
		'0231' => 'Urząd Skarbowy w Zgorzelcu',
		'0232' => 'Urząd Skarbowy w Złotoryi',
		'3036' => 'Urząd Skarbowy w Złotowie',
		'1444' => 'Urząd Skarbowy w Zwoleniu',
		'0810' => 'Urząd Skarbowy w Żaganiu',
		'0811' => 'Urząd Skarbowy w Żarach',
		'0421' => 'Urząd Skarbowy w Żninie',
		'2435' => 'Urząd Skarbowy w Żorach',
		'1445' => 'Urząd Skarbowy w Żurominie',
		'1446' => 'Urząd Skarbowy w Żyrardowie',
		'2436' => 'Urząd Skarbowy w Żywcu',
		'1431' => 'Urząd Skarbowy Warszawa-Bemowo',
		'1432' => 'Urząd Skarbowy Warszawa-Bielany',
		'1433' => 'Urząd Skarbowy Warszawa-Mokotów',
		'1434' => 'Urząd Skarbowy Warszawa-Praga',
		'1437' => 'Urząd Skarbowy Warszawa-Targówek',
		'1438' => 'Urząd Skarbowy Warszawa-Ursynów',
		'1439' => 'Urząd Skarbowy Warszawa-Wawer',
		'1440' => 'Urząd Skarbowy Warszawa-Wola',
		'0420' => 'Urząd Skarbowy We Włocławku',
		'0619' => 'Urząd Skarbowy We Włodawie',
		'2615' => 'Urząd Skarbowy We Włoszczowie',
		'3035' => 'Urząd Skarbowy We Wrześni',
		'0814' => 'Urząd Skarbowy We Wschowie',
		'0224' => 'Urząd Skarbowy Wrocław-Fabryczna',
		'0225' => 'Urząd Skarbowy Wrocław-Krzyki',
		'0226' => 'Urząd Skarbowy Wrocław-Psie Pole',
		'0227' => 'Urząd Skarbowy Wrocław-Stare Miasto',
		'0228' => 'Urząd Skarbowy Wrocław-Śródmieście',
		'2871' => 'Warmińsko-Mazurski Urząd Skarbowy w Olsztynie',
		'3271' => 'Zachodniopomorski Urząd Skarbowy w Szczecinie',
	);
	return $data;
}
